#!/bin/zsh
set -euo pipefail
OUT="/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/reference/emerald-slices-5x10-custom-colors"
rm -rf "$OUT"/colors "$OUT"/tmp
mkdir -p "$OUT"/colors "$OUT"/tmp
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_01.png" -resize 64x64! "$OUT/tmp/base_01.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_02.png" -resize 64x64! "$OUT/tmp/base_02.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_03.png" -resize 64x64! "$OUT/tmp/base_03.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_04.png" -resize 64x64! "$OUT/tmp/base_04.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_05.png" -resize 64x64! "$OUT/tmp/base_05.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_06.png" -resize 64x64! "$OUT/tmp/base_06.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_07.png" -resize 64x64! "$OUT/tmp/base_07.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_08.png" -resize 64x64! "$OUT/tmp/base_08.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_09.png" -resize 64x64! "$OUT/tmp/base_09.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_10.png" -resize 64x64! "$OUT/tmp/base_10.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_11.png" -resize 64x64! "$OUT/tmp/base_11.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_12.png" -resize 64x64! "$OUT/tmp/base_12.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_13.png" -resize 64x64! "$OUT/tmp/base_13.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_14.png" -resize 64x64! "$OUT/tmp/base_14.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_15.png" -resize 64x64! "$OUT/tmp/base_15.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_16.png" -resize 64x64! "$OUT/tmp/base_16.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_17.png" -resize 64x64! "$OUT/tmp/base_17.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_18.png" -resize 64x64! "$OUT/tmp/base_18.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_19.png" -resize 64x64! "$OUT/tmp/base_19.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_20.png" -resize 64x64! "$OUT/tmp/base_20.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_21.png" -resize 64x64! "$OUT/tmp/base_21.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_22.png" -resize 64x64! "$OUT/tmp/base_22.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_23.png" -resize 64x64! "$OUT/tmp/base_23.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_24.png" -resize 64x64! "$OUT/tmp/base_24.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_25.png" -resize 64x64! "$OUT/tmp/base_25.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_26.png" -resize 64x64! "$OUT/tmp/base_26.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_27.png" -resize 64x64! "$OUT/tmp/base_27.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_28.png" -resize 64x64! "$OUT/tmp/base_28.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_29.png" -resize 64x64! "$OUT/tmp/base_29.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_30.png" -resize 64x64! "$OUT/tmp/base_30.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_31.png" -resize 64x64! "$OUT/tmp/base_31.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_32.png" -resize 64x64! "$OUT/tmp/base_32.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_33.png" -resize 64x64! "$OUT/tmp/base_33.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_34.png" -resize 64x64! "$OUT/tmp/base_34.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_35.png" -resize 64x64! "$OUT/tmp/base_35.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_36.png" -resize 64x64! "$OUT/tmp/base_36.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_37.png" -resize 64x64! "$OUT/tmp/base_37.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_38.png" -resize 64x64! "$OUT/tmp/base_38.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_39.png" -resize 64x64! "$OUT/tmp/base_39.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_40.png" -resize 64x64! "$OUT/tmp/base_40.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_41.png" -resize 64x64! "$OUT/tmp/base_41.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_42.png" -resize 64x64! "$OUT/tmp/base_42.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_43.png" -resize 64x64! "$OUT/tmp/base_43.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_44.png" -resize 64x64! "$OUT/tmp/base_44.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_45.png" -resize 64x64! "$OUT/tmp/base_45.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_46.png" -resize 64x64! "$OUT/tmp/base_46.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_47.png" -resize 64x64! "$OUT/tmp/base_47.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_48.png" -resize 64x64! "$OUT/tmp/base_48.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_49.png" -resize 64x64! "$OUT/tmp/base_49.png"
magick "/Users/garretcoffman/Documents/VSMods/VSMineralMasonry/textures/emerald-slices/5x10/images/Untitled-2_50.png" -resize 64x64! "$OUT/tmp/base_50.png"
mkdir -p "$OUT/colors/lignite/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(92,70,50)" -colorize 100 "$OUT/colors/lignite/tiles/lignite_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/lignite/tiles/lignite_01.png" -geometry +1+1 -composite \
  "$OUT/colors/lignite/tiles/lignite_02.png" -geometry +66+1 -composite \
  "$OUT/colors/lignite/tiles/lignite_03.png" -geometry +131+1 -composite \
  "$OUT/colors/lignite/tiles/lignite_04.png" -geometry +196+1 -composite \
  "$OUT/colors/lignite/tiles/lignite_05.png" -geometry +261+1 -composite \
  "$OUT/colors/lignite/tiles/lignite_06.png" -geometry +326+1 -composite \
  "$OUT/colors/lignite/tiles/lignite_07.png" -geometry +391+1 -composite \
  "$OUT/colors/lignite/tiles/lignite_08.png" -geometry +456+1 -composite \
  "$OUT/colors/lignite/tiles/lignite_09.png" -geometry +521+1 -composite \
  "$OUT/colors/lignite/tiles/lignite_10.png" -geometry +586+1 -composite \
  "$OUT/colors/lignite/tiles/lignite_11.png" -geometry +1+66 -composite \
  "$OUT/colors/lignite/tiles/lignite_12.png" -geometry +66+66 -composite \
  "$OUT/colors/lignite/tiles/lignite_13.png" -geometry +131+66 -composite \
  "$OUT/colors/lignite/tiles/lignite_14.png" -geometry +196+66 -composite \
  "$OUT/colors/lignite/tiles/lignite_15.png" -geometry +261+66 -composite \
  "$OUT/colors/lignite/tiles/lignite_16.png" -geometry +326+66 -composite \
  "$OUT/colors/lignite/tiles/lignite_17.png" -geometry +391+66 -composite \
  "$OUT/colors/lignite/tiles/lignite_18.png" -geometry +456+66 -composite \
  "$OUT/colors/lignite/tiles/lignite_19.png" -geometry +521+66 -composite \
  "$OUT/colors/lignite/tiles/lignite_20.png" -geometry +586+66 -composite \
  "$OUT/colors/lignite/tiles/lignite_21.png" -geometry +1+131 -composite \
  "$OUT/colors/lignite/tiles/lignite_22.png" -geometry +66+131 -composite \
  "$OUT/colors/lignite/tiles/lignite_23.png" -geometry +131+131 -composite \
  "$OUT/colors/lignite/tiles/lignite_24.png" -geometry +196+131 -composite \
  "$OUT/colors/lignite/tiles/lignite_25.png" -geometry +261+131 -composite \
  "$OUT/colors/lignite/tiles/lignite_26.png" -geometry +326+131 -composite \
  "$OUT/colors/lignite/tiles/lignite_27.png" -geometry +391+131 -composite \
  "$OUT/colors/lignite/tiles/lignite_28.png" -geometry +456+131 -composite \
  "$OUT/colors/lignite/tiles/lignite_29.png" -geometry +521+131 -composite \
  "$OUT/colors/lignite/tiles/lignite_30.png" -geometry +586+131 -composite \
  "$OUT/colors/lignite/tiles/lignite_31.png" -geometry +1+196 -composite \
  "$OUT/colors/lignite/tiles/lignite_32.png" -geometry +66+196 -composite \
  "$OUT/colors/lignite/tiles/lignite_33.png" -geometry +131+196 -composite \
  "$OUT/colors/lignite/tiles/lignite_34.png" -geometry +196+196 -composite \
  "$OUT/colors/lignite/tiles/lignite_35.png" -geometry +261+196 -composite \
  "$OUT/colors/lignite/tiles/lignite_36.png" -geometry +326+196 -composite \
  "$OUT/colors/lignite/tiles/lignite_37.png" -geometry +391+196 -composite \
  "$OUT/colors/lignite/tiles/lignite_38.png" -geometry +456+196 -composite \
  "$OUT/colors/lignite/tiles/lignite_39.png" -geometry +521+196 -composite \
  "$OUT/colors/lignite/tiles/lignite_40.png" -geometry +586+196 -composite \
  "$OUT/colors/lignite/tiles/lignite_41.png" -geometry +1+261 -composite \
  "$OUT/colors/lignite/tiles/lignite_42.png" -geometry +66+261 -composite \
  "$OUT/colors/lignite/tiles/lignite_43.png" -geometry +131+261 -composite \
  "$OUT/colors/lignite/tiles/lignite_44.png" -geometry +196+261 -composite \
  "$OUT/colors/lignite/tiles/lignite_45.png" -geometry +261+261 -composite \
  "$OUT/colors/lignite/tiles/lignite_46.png" -geometry +326+261 -composite \
  "$OUT/colors/lignite/tiles/lignite_47.png" -geometry +391+261 -composite \
  "$OUT/colors/lignite/tiles/lignite_48.png" -geometry +456+261 -composite \
  "$OUT/colors/lignite/tiles/lignite_49.png" -geometry +521+261 -composite \
  "$OUT/colors/lignite/tiles/lignite_50.png" -geometry +586+261 -composite "$OUT/lignite-reconstructed.png"
mkdir -p "$OUT/colors/quartz/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(210,210,200)" -colorize 100 "$OUT/colors/quartz/tiles/quartz_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/quartz/tiles/quartz_01.png" -geometry +1+1 -composite \
  "$OUT/colors/quartz/tiles/quartz_02.png" -geometry +66+1 -composite \
  "$OUT/colors/quartz/tiles/quartz_03.png" -geometry +131+1 -composite \
  "$OUT/colors/quartz/tiles/quartz_04.png" -geometry +196+1 -composite \
  "$OUT/colors/quartz/tiles/quartz_05.png" -geometry +261+1 -composite \
  "$OUT/colors/quartz/tiles/quartz_06.png" -geometry +326+1 -composite \
  "$OUT/colors/quartz/tiles/quartz_07.png" -geometry +391+1 -composite \
  "$OUT/colors/quartz/tiles/quartz_08.png" -geometry +456+1 -composite \
  "$OUT/colors/quartz/tiles/quartz_09.png" -geometry +521+1 -composite \
  "$OUT/colors/quartz/tiles/quartz_10.png" -geometry +586+1 -composite \
  "$OUT/colors/quartz/tiles/quartz_11.png" -geometry +1+66 -composite \
  "$OUT/colors/quartz/tiles/quartz_12.png" -geometry +66+66 -composite \
  "$OUT/colors/quartz/tiles/quartz_13.png" -geometry +131+66 -composite \
  "$OUT/colors/quartz/tiles/quartz_14.png" -geometry +196+66 -composite \
  "$OUT/colors/quartz/tiles/quartz_15.png" -geometry +261+66 -composite \
  "$OUT/colors/quartz/tiles/quartz_16.png" -geometry +326+66 -composite \
  "$OUT/colors/quartz/tiles/quartz_17.png" -geometry +391+66 -composite \
  "$OUT/colors/quartz/tiles/quartz_18.png" -geometry +456+66 -composite \
  "$OUT/colors/quartz/tiles/quartz_19.png" -geometry +521+66 -composite \
  "$OUT/colors/quartz/tiles/quartz_20.png" -geometry +586+66 -composite \
  "$OUT/colors/quartz/tiles/quartz_21.png" -geometry +1+131 -composite \
  "$OUT/colors/quartz/tiles/quartz_22.png" -geometry +66+131 -composite \
  "$OUT/colors/quartz/tiles/quartz_23.png" -geometry +131+131 -composite \
  "$OUT/colors/quartz/tiles/quartz_24.png" -geometry +196+131 -composite \
  "$OUT/colors/quartz/tiles/quartz_25.png" -geometry +261+131 -composite \
  "$OUT/colors/quartz/tiles/quartz_26.png" -geometry +326+131 -composite \
  "$OUT/colors/quartz/tiles/quartz_27.png" -geometry +391+131 -composite \
  "$OUT/colors/quartz/tiles/quartz_28.png" -geometry +456+131 -composite \
  "$OUT/colors/quartz/tiles/quartz_29.png" -geometry +521+131 -composite \
  "$OUT/colors/quartz/tiles/quartz_30.png" -geometry +586+131 -composite \
  "$OUT/colors/quartz/tiles/quartz_31.png" -geometry +1+196 -composite \
  "$OUT/colors/quartz/tiles/quartz_32.png" -geometry +66+196 -composite \
  "$OUT/colors/quartz/tiles/quartz_33.png" -geometry +131+196 -composite \
  "$OUT/colors/quartz/tiles/quartz_34.png" -geometry +196+196 -composite \
  "$OUT/colors/quartz/tiles/quartz_35.png" -geometry +261+196 -composite \
  "$OUT/colors/quartz/tiles/quartz_36.png" -geometry +326+196 -composite \
  "$OUT/colors/quartz/tiles/quartz_37.png" -geometry +391+196 -composite \
  "$OUT/colors/quartz/tiles/quartz_38.png" -geometry +456+196 -composite \
  "$OUT/colors/quartz/tiles/quartz_39.png" -geometry +521+196 -composite \
  "$OUT/colors/quartz/tiles/quartz_40.png" -geometry +586+196 -composite \
  "$OUT/colors/quartz/tiles/quartz_41.png" -geometry +1+261 -composite \
  "$OUT/colors/quartz/tiles/quartz_42.png" -geometry +66+261 -composite \
  "$OUT/colors/quartz/tiles/quartz_43.png" -geometry +131+261 -composite \
  "$OUT/colors/quartz/tiles/quartz_44.png" -geometry +196+261 -composite \
  "$OUT/colors/quartz/tiles/quartz_45.png" -geometry +261+261 -composite \
  "$OUT/colors/quartz/tiles/quartz_46.png" -geometry +326+261 -composite \
  "$OUT/colors/quartz/tiles/quartz_47.png" -geometry +391+261 -composite \
  "$OUT/colors/quartz/tiles/quartz_48.png" -geometry +456+261 -composite \
  "$OUT/colors/quartz/tiles/quartz_49.png" -geometry +521+261 -composite \
  "$OUT/colors/quartz/tiles/quartz_50.png" -geometry +586+261 -composite "$OUT/quartz-reconstructed.png"
mkdir -p "$OUT/colors/magnetite/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(58,63,69)" -colorize 100 "$OUT/colors/magnetite/tiles/magnetite_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/magnetite/tiles/magnetite_01.png" -geometry +1+1 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_02.png" -geometry +66+1 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_03.png" -geometry +131+1 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_04.png" -geometry +196+1 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_05.png" -geometry +261+1 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_06.png" -geometry +326+1 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_07.png" -geometry +391+1 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_08.png" -geometry +456+1 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_09.png" -geometry +521+1 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_10.png" -geometry +586+1 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_11.png" -geometry +1+66 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_12.png" -geometry +66+66 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_13.png" -geometry +131+66 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_14.png" -geometry +196+66 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_15.png" -geometry +261+66 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_16.png" -geometry +326+66 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_17.png" -geometry +391+66 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_18.png" -geometry +456+66 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_19.png" -geometry +521+66 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_20.png" -geometry +586+66 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_21.png" -geometry +1+131 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_22.png" -geometry +66+131 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_23.png" -geometry +131+131 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_24.png" -geometry +196+131 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_25.png" -geometry +261+131 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_26.png" -geometry +326+131 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_27.png" -geometry +391+131 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_28.png" -geometry +456+131 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_29.png" -geometry +521+131 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_30.png" -geometry +586+131 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_31.png" -geometry +1+196 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_32.png" -geometry +66+196 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_33.png" -geometry +131+196 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_34.png" -geometry +196+196 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_35.png" -geometry +261+196 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_36.png" -geometry +326+196 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_37.png" -geometry +391+196 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_38.png" -geometry +456+196 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_39.png" -geometry +521+196 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_40.png" -geometry +586+196 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_41.png" -geometry +1+261 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_42.png" -geometry +66+261 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_43.png" -geometry +131+261 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_44.png" -geometry +196+261 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_45.png" -geometry +261+261 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_46.png" -geometry +326+261 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_47.png" -geometry +391+261 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_48.png" -geometry +456+261 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_49.png" -geometry +521+261 -composite \
  "$OUT/colors/magnetite/tiles/magnetite_50.png" -geometry +586+261 -composite "$OUT/magnetite-reconstructed.png"
mkdir -p "$OUT/colors/hematite/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(110,35,30)" -colorize 100 "$OUT/colors/hematite/tiles/hematite_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/hematite/tiles/hematite_01.png" -geometry +1+1 -composite \
  "$OUT/colors/hematite/tiles/hematite_02.png" -geometry +66+1 -composite \
  "$OUT/colors/hematite/tiles/hematite_03.png" -geometry +131+1 -composite \
  "$OUT/colors/hematite/tiles/hematite_04.png" -geometry +196+1 -composite \
  "$OUT/colors/hematite/tiles/hematite_05.png" -geometry +261+1 -composite \
  "$OUT/colors/hematite/tiles/hematite_06.png" -geometry +326+1 -composite \
  "$OUT/colors/hematite/tiles/hematite_07.png" -geometry +391+1 -composite \
  "$OUT/colors/hematite/tiles/hematite_08.png" -geometry +456+1 -composite \
  "$OUT/colors/hematite/tiles/hematite_09.png" -geometry +521+1 -composite \
  "$OUT/colors/hematite/tiles/hematite_10.png" -geometry +586+1 -composite \
  "$OUT/colors/hematite/tiles/hematite_11.png" -geometry +1+66 -composite \
  "$OUT/colors/hematite/tiles/hematite_12.png" -geometry +66+66 -composite \
  "$OUT/colors/hematite/tiles/hematite_13.png" -geometry +131+66 -composite \
  "$OUT/colors/hematite/tiles/hematite_14.png" -geometry +196+66 -composite \
  "$OUT/colors/hematite/tiles/hematite_15.png" -geometry +261+66 -composite \
  "$OUT/colors/hematite/tiles/hematite_16.png" -geometry +326+66 -composite \
  "$OUT/colors/hematite/tiles/hematite_17.png" -geometry +391+66 -composite \
  "$OUT/colors/hematite/tiles/hematite_18.png" -geometry +456+66 -composite \
  "$OUT/colors/hematite/tiles/hematite_19.png" -geometry +521+66 -composite \
  "$OUT/colors/hematite/tiles/hematite_20.png" -geometry +586+66 -composite \
  "$OUT/colors/hematite/tiles/hematite_21.png" -geometry +1+131 -composite \
  "$OUT/colors/hematite/tiles/hematite_22.png" -geometry +66+131 -composite \
  "$OUT/colors/hematite/tiles/hematite_23.png" -geometry +131+131 -composite \
  "$OUT/colors/hematite/tiles/hematite_24.png" -geometry +196+131 -composite \
  "$OUT/colors/hematite/tiles/hematite_25.png" -geometry +261+131 -composite \
  "$OUT/colors/hematite/tiles/hematite_26.png" -geometry +326+131 -composite \
  "$OUT/colors/hematite/tiles/hematite_27.png" -geometry +391+131 -composite \
  "$OUT/colors/hematite/tiles/hematite_28.png" -geometry +456+131 -composite \
  "$OUT/colors/hematite/tiles/hematite_29.png" -geometry +521+131 -composite \
  "$OUT/colors/hematite/tiles/hematite_30.png" -geometry +586+131 -composite \
  "$OUT/colors/hematite/tiles/hematite_31.png" -geometry +1+196 -composite \
  "$OUT/colors/hematite/tiles/hematite_32.png" -geometry +66+196 -composite \
  "$OUT/colors/hematite/tiles/hematite_33.png" -geometry +131+196 -composite \
  "$OUT/colors/hematite/tiles/hematite_34.png" -geometry +196+196 -composite \
  "$OUT/colors/hematite/tiles/hematite_35.png" -geometry +261+196 -composite \
  "$OUT/colors/hematite/tiles/hematite_36.png" -geometry +326+196 -composite \
  "$OUT/colors/hematite/tiles/hematite_37.png" -geometry +391+196 -composite \
  "$OUT/colors/hematite/tiles/hematite_38.png" -geometry +456+196 -composite \
  "$OUT/colors/hematite/tiles/hematite_39.png" -geometry +521+196 -composite \
  "$OUT/colors/hematite/tiles/hematite_40.png" -geometry +586+196 -composite \
  "$OUT/colors/hematite/tiles/hematite_41.png" -geometry +1+261 -composite \
  "$OUT/colors/hematite/tiles/hematite_42.png" -geometry +66+261 -composite \
  "$OUT/colors/hematite/tiles/hematite_43.png" -geometry +131+261 -composite \
  "$OUT/colors/hematite/tiles/hematite_44.png" -geometry +196+261 -composite \
  "$OUT/colors/hematite/tiles/hematite_45.png" -geometry +261+261 -composite \
  "$OUT/colors/hematite/tiles/hematite_46.png" -geometry +326+261 -composite \
  "$OUT/colors/hematite/tiles/hematite_47.png" -geometry +391+261 -composite \
  "$OUT/colors/hematite/tiles/hematite_48.png" -geometry +456+261 -composite \
  "$OUT/colors/hematite/tiles/hematite_49.png" -geometry +521+261 -composite \
  "$OUT/colors/hematite/tiles/hematite_50.png" -geometry +586+261 -composite "$OUT/hematite-reconstructed.png"
mkdir -p "$OUT/colors/cinnabar/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(200,70,80)" -colorize 100 "$OUT/colors/cinnabar/tiles/cinnabar_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/cinnabar/tiles/cinnabar_01.png" -geometry +1+1 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_02.png" -geometry +66+1 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_03.png" -geometry +131+1 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_04.png" -geometry +196+1 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_05.png" -geometry +261+1 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_06.png" -geometry +326+1 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_07.png" -geometry +391+1 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_08.png" -geometry +456+1 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_09.png" -geometry +521+1 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_10.png" -geometry +586+1 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_11.png" -geometry +1+66 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_12.png" -geometry +66+66 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_13.png" -geometry +131+66 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_14.png" -geometry +196+66 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_15.png" -geometry +261+66 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_16.png" -geometry +326+66 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_17.png" -geometry +391+66 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_18.png" -geometry +456+66 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_19.png" -geometry +521+66 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_20.png" -geometry +586+66 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_21.png" -geometry +1+131 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_22.png" -geometry +66+131 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_23.png" -geometry +131+131 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_24.png" -geometry +196+131 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_25.png" -geometry +261+131 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_26.png" -geometry +326+131 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_27.png" -geometry +391+131 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_28.png" -geometry +456+131 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_29.png" -geometry +521+131 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_30.png" -geometry +586+131 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_31.png" -geometry +1+196 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_32.png" -geometry +66+196 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_33.png" -geometry +131+196 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_34.png" -geometry +196+196 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_35.png" -geometry +261+196 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_36.png" -geometry +326+196 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_37.png" -geometry +391+196 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_38.png" -geometry +456+196 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_39.png" -geometry +521+196 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_40.png" -geometry +586+196 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_41.png" -geometry +1+261 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_42.png" -geometry +66+261 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_43.png" -geometry +131+261 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_44.png" -geometry +196+261 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_45.png" -geometry +261+261 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_46.png" -geometry +326+261 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_47.png" -geometry +391+261 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_48.png" -geometry +456+261 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_49.png" -geometry +521+261 -composite \
  "$OUT/colors/cinnabar/tiles/cinnabar_50.png" -geometry +586+261 -composite "$OUT/cinnabar-reconstructed.png"
mkdir -p "$OUT/colors/olivine/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(120,150,60)" -colorize 100 "$OUT/colors/olivine/tiles/olivine_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/olivine/tiles/olivine_01.png" -geometry +1+1 -composite \
  "$OUT/colors/olivine/tiles/olivine_02.png" -geometry +66+1 -composite \
  "$OUT/colors/olivine/tiles/olivine_03.png" -geometry +131+1 -composite \
  "$OUT/colors/olivine/tiles/olivine_04.png" -geometry +196+1 -composite \
  "$OUT/colors/olivine/tiles/olivine_05.png" -geometry +261+1 -composite \
  "$OUT/colors/olivine/tiles/olivine_06.png" -geometry +326+1 -composite \
  "$OUT/colors/olivine/tiles/olivine_07.png" -geometry +391+1 -composite \
  "$OUT/colors/olivine/tiles/olivine_08.png" -geometry +456+1 -composite \
  "$OUT/colors/olivine/tiles/olivine_09.png" -geometry +521+1 -composite \
  "$OUT/colors/olivine/tiles/olivine_10.png" -geometry +586+1 -composite \
  "$OUT/colors/olivine/tiles/olivine_11.png" -geometry +1+66 -composite \
  "$OUT/colors/olivine/tiles/olivine_12.png" -geometry +66+66 -composite \
  "$OUT/colors/olivine/tiles/olivine_13.png" -geometry +131+66 -composite \
  "$OUT/colors/olivine/tiles/olivine_14.png" -geometry +196+66 -composite \
  "$OUT/colors/olivine/tiles/olivine_15.png" -geometry +261+66 -composite \
  "$OUT/colors/olivine/tiles/olivine_16.png" -geometry +326+66 -composite \
  "$OUT/colors/olivine/tiles/olivine_17.png" -geometry +391+66 -composite \
  "$OUT/colors/olivine/tiles/olivine_18.png" -geometry +456+66 -composite \
  "$OUT/colors/olivine/tiles/olivine_19.png" -geometry +521+66 -composite \
  "$OUT/colors/olivine/tiles/olivine_20.png" -geometry +586+66 -composite \
  "$OUT/colors/olivine/tiles/olivine_21.png" -geometry +1+131 -composite \
  "$OUT/colors/olivine/tiles/olivine_22.png" -geometry +66+131 -composite \
  "$OUT/colors/olivine/tiles/olivine_23.png" -geometry +131+131 -composite \
  "$OUT/colors/olivine/tiles/olivine_24.png" -geometry +196+131 -composite \
  "$OUT/colors/olivine/tiles/olivine_25.png" -geometry +261+131 -composite \
  "$OUT/colors/olivine/tiles/olivine_26.png" -geometry +326+131 -composite \
  "$OUT/colors/olivine/tiles/olivine_27.png" -geometry +391+131 -composite \
  "$OUT/colors/olivine/tiles/olivine_28.png" -geometry +456+131 -composite \
  "$OUT/colors/olivine/tiles/olivine_29.png" -geometry +521+131 -composite \
  "$OUT/colors/olivine/tiles/olivine_30.png" -geometry +586+131 -composite \
  "$OUT/colors/olivine/tiles/olivine_31.png" -geometry +1+196 -composite \
  "$OUT/colors/olivine/tiles/olivine_32.png" -geometry +66+196 -composite \
  "$OUT/colors/olivine/tiles/olivine_33.png" -geometry +131+196 -composite \
  "$OUT/colors/olivine/tiles/olivine_34.png" -geometry +196+196 -composite \
  "$OUT/colors/olivine/tiles/olivine_35.png" -geometry +261+196 -composite \
  "$OUT/colors/olivine/tiles/olivine_36.png" -geometry +326+196 -composite \
  "$OUT/colors/olivine/tiles/olivine_37.png" -geometry +391+196 -composite \
  "$OUT/colors/olivine/tiles/olivine_38.png" -geometry +456+196 -composite \
  "$OUT/colors/olivine/tiles/olivine_39.png" -geometry +521+196 -composite \
  "$OUT/colors/olivine/tiles/olivine_40.png" -geometry +586+196 -composite \
  "$OUT/colors/olivine/tiles/olivine_41.png" -geometry +1+261 -composite \
  "$OUT/colors/olivine/tiles/olivine_42.png" -geometry +66+261 -composite \
  "$OUT/colors/olivine/tiles/olivine_43.png" -geometry +131+261 -composite \
  "$OUT/colors/olivine/tiles/olivine_44.png" -geometry +196+261 -composite \
  "$OUT/colors/olivine/tiles/olivine_45.png" -geometry +261+261 -composite \
  "$OUT/colors/olivine/tiles/olivine_46.png" -geometry +326+261 -composite \
  "$OUT/colors/olivine/tiles/olivine_47.png" -geometry +391+261 -composite \
  "$OUT/colors/olivine/tiles/olivine_48.png" -geometry +456+261 -composite \
  "$OUT/colors/olivine/tiles/olivine_49.png" -geometry +521+261 -composite \
  "$OUT/colors/olivine/tiles/olivine_50.png" -geometry +586+261 -composite "$OUT/olivine-reconstructed.png"
mkdir -p "$OUT/colors/malachite/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(40,150,90)" -colorize 100 "$OUT/colors/malachite/tiles/malachite_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/malachite/tiles/malachite_01.png" -geometry +1+1 -composite \
  "$OUT/colors/malachite/tiles/malachite_02.png" -geometry +66+1 -composite \
  "$OUT/colors/malachite/tiles/malachite_03.png" -geometry +131+1 -composite \
  "$OUT/colors/malachite/tiles/malachite_04.png" -geometry +196+1 -composite \
  "$OUT/colors/malachite/tiles/malachite_05.png" -geometry +261+1 -composite \
  "$OUT/colors/malachite/tiles/malachite_06.png" -geometry +326+1 -composite \
  "$OUT/colors/malachite/tiles/malachite_07.png" -geometry +391+1 -composite \
  "$OUT/colors/malachite/tiles/malachite_08.png" -geometry +456+1 -composite \
  "$OUT/colors/malachite/tiles/malachite_09.png" -geometry +521+1 -composite \
  "$OUT/colors/malachite/tiles/malachite_10.png" -geometry +586+1 -composite \
  "$OUT/colors/malachite/tiles/malachite_11.png" -geometry +1+66 -composite \
  "$OUT/colors/malachite/tiles/malachite_12.png" -geometry +66+66 -composite \
  "$OUT/colors/malachite/tiles/malachite_13.png" -geometry +131+66 -composite \
  "$OUT/colors/malachite/tiles/malachite_14.png" -geometry +196+66 -composite \
  "$OUT/colors/malachite/tiles/malachite_15.png" -geometry +261+66 -composite \
  "$OUT/colors/malachite/tiles/malachite_16.png" -geometry +326+66 -composite \
  "$OUT/colors/malachite/tiles/malachite_17.png" -geometry +391+66 -composite \
  "$OUT/colors/malachite/tiles/malachite_18.png" -geometry +456+66 -composite \
  "$OUT/colors/malachite/tiles/malachite_19.png" -geometry +521+66 -composite \
  "$OUT/colors/malachite/tiles/malachite_20.png" -geometry +586+66 -composite \
  "$OUT/colors/malachite/tiles/malachite_21.png" -geometry +1+131 -composite \
  "$OUT/colors/malachite/tiles/malachite_22.png" -geometry +66+131 -composite \
  "$OUT/colors/malachite/tiles/malachite_23.png" -geometry +131+131 -composite \
  "$OUT/colors/malachite/tiles/malachite_24.png" -geometry +196+131 -composite \
  "$OUT/colors/malachite/tiles/malachite_25.png" -geometry +261+131 -composite \
  "$OUT/colors/malachite/tiles/malachite_26.png" -geometry +326+131 -composite \
  "$OUT/colors/malachite/tiles/malachite_27.png" -geometry +391+131 -composite \
  "$OUT/colors/malachite/tiles/malachite_28.png" -geometry +456+131 -composite \
  "$OUT/colors/malachite/tiles/malachite_29.png" -geometry +521+131 -composite \
  "$OUT/colors/malachite/tiles/malachite_30.png" -geometry +586+131 -composite \
  "$OUT/colors/malachite/tiles/malachite_31.png" -geometry +1+196 -composite \
  "$OUT/colors/malachite/tiles/malachite_32.png" -geometry +66+196 -composite \
  "$OUT/colors/malachite/tiles/malachite_33.png" -geometry +131+196 -composite \
  "$OUT/colors/malachite/tiles/malachite_34.png" -geometry +196+196 -composite \
  "$OUT/colors/malachite/tiles/malachite_35.png" -geometry +261+196 -composite \
  "$OUT/colors/malachite/tiles/malachite_36.png" -geometry +326+196 -composite \
  "$OUT/colors/malachite/tiles/malachite_37.png" -geometry +391+196 -composite \
  "$OUT/colors/malachite/tiles/malachite_38.png" -geometry +456+196 -composite \
  "$OUT/colors/malachite/tiles/malachite_39.png" -geometry +521+196 -composite \
  "$OUT/colors/malachite/tiles/malachite_40.png" -geometry +586+196 -composite \
  "$OUT/colors/malachite/tiles/malachite_41.png" -geometry +1+261 -composite \
  "$OUT/colors/malachite/tiles/malachite_42.png" -geometry +66+261 -composite \
  "$OUT/colors/malachite/tiles/malachite_43.png" -geometry +131+261 -composite \
  "$OUT/colors/malachite/tiles/malachite_44.png" -geometry +196+261 -composite \
  "$OUT/colors/malachite/tiles/malachite_45.png" -geometry +261+261 -composite \
  "$OUT/colors/malachite/tiles/malachite_46.png" -geometry +326+261 -composite \
  "$OUT/colors/malachite/tiles/malachite_47.png" -geometry +391+261 -composite \
  "$OUT/colors/malachite/tiles/malachite_48.png" -geometry +456+261 -composite \
  "$OUT/colors/malachite/tiles/malachite_49.png" -geometry +521+261 -composite \
  "$OUT/colors/malachite/tiles/malachite_50.png" -geometry +586+261 -composite "$OUT/malachite-reconstructed.png"
mkdir -p "$OUT/colors/emerald/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(0,140,90)" -colorize 100 "$OUT/colors/emerald/tiles/emerald_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/emerald/tiles/emerald_01.png" -geometry +1+1 -composite \
  "$OUT/colors/emerald/tiles/emerald_02.png" -geometry +66+1 -composite \
  "$OUT/colors/emerald/tiles/emerald_03.png" -geometry +131+1 -composite \
  "$OUT/colors/emerald/tiles/emerald_04.png" -geometry +196+1 -composite \
  "$OUT/colors/emerald/tiles/emerald_05.png" -geometry +261+1 -composite \
  "$OUT/colors/emerald/tiles/emerald_06.png" -geometry +326+1 -composite \
  "$OUT/colors/emerald/tiles/emerald_07.png" -geometry +391+1 -composite \
  "$OUT/colors/emerald/tiles/emerald_08.png" -geometry +456+1 -composite \
  "$OUT/colors/emerald/tiles/emerald_09.png" -geometry +521+1 -composite \
  "$OUT/colors/emerald/tiles/emerald_10.png" -geometry +586+1 -composite \
  "$OUT/colors/emerald/tiles/emerald_11.png" -geometry +1+66 -composite \
  "$OUT/colors/emerald/tiles/emerald_12.png" -geometry +66+66 -composite \
  "$OUT/colors/emerald/tiles/emerald_13.png" -geometry +131+66 -composite \
  "$OUT/colors/emerald/tiles/emerald_14.png" -geometry +196+66 -composite \
  "$OUT/colors/emerald/tiles/emerald_15.png" -geometry +261+66 -composite \
  "$OUT/colors/emerald/tiles/emerald_16.png" -geometry +326+66 -composite \
  "$OUT/colors/emerald/tiles/emerald_17.png" -geometry +391+66 -composite \
  "$OUT/colors/emerald/tiles/emerald_18.png" -geometry +456+66 -composite \
  "$OUT/colors/emerald/tiles/emerald_19.png" -geometry +521+66 -composite \
  "$OUT/colors/emerald/tiles/emerald_20.png" -geometry +586+66 -composite \
  "$OUT/colors/emerald/tiles/emerald_21.png" -geometry +1+131 -composite \
  "$OUT/colors/emerald/tiles/emerald_22.png" -geometry +66+131 -composite \
  "$OUT/colors/emerald/tiles/emerald_23.png" -geometry +131+131 -composite \
  "$OUT/colors/emerald/tiles/emerald_24.png" -geometry +196+131 -composite \
  "$OUT/colors/emerald/tiles/emerald_25.png" -geometry +261+131 -composite \
  "$OUT/colors/emerald/tiles/emerald_26.png" -geometry +326+131 -composite \
  "$OUT/colors/emerald/tiles/emerald_27.png" -geometry +391+131 -composite \
  "$OUT/colors/emerald/tiles/emerald_28.png" -geometry +456+131 -composite \
  "$OUT/colors/emerald/tiles/emerald_29.png" -geometry +521+131 -composite \
  "$OUT/colors/emerald/tiles/emerald_30.png" -geometry +586+131 -composite \
  "$OUT/colors/emerald/tiles/emerald_31.png" -geometry +1+196 -composite \
  "$OUT/colors/emerald/tiles/emerald_32.png" -geometry +66+196 -composite \
  "$OUT/colors/emerald/tiles/emerald_33.png" -geometry +131+196 -composite \
  "$OUT/colors/emerald/tiles/emerald_34.png" -geometry +196+196 -composite \
  "$OUT/colors/emerald/tiles/emerald_35.png" -geometry +261+196 -composite \
  "$OUT/colors/emerald/tiles/emerald_36.png" -geometry +326+196 -composite \
  "$OUT/colors/emerald/tiles/emerald_37.png" -geometry +391+196 -composite \
  "$OUT/colors/emerald/tiles/emerald_38.png" -geometry +456+196 -composite \
  "$OUT/colors/emerald/tiles/emerald_39.png" -geometry +521+196 -composite \
  "$OUT/colors/emerald/tiles/emerald_40.png" -geometry +586+196 -composite \
  "$OUT/colors/emerald/tiles/emerald_41.png" -geometry +1+261 -composite \
  "$OUT/colors/emerald/tiles/emerald_42.png" -geometry +66+261 -composite \
  "$OUT/colors/emerald/tiles/emerald_43.png" -geometry +131+261 -composite \
  "$OUT/colors/emerald/tiles/emerald_44.png" -geometry +196+261 -composite \
  "$OUT/colors/emerald/tiles/emerald_45.png" -geometry +261+261 -composite \
  "$OUT/colors/emerald/tiles/emerald_46.png" -geometry +326+261 -composite \
  "$OUT/colors/emerald/tiles/emerald_47.png" -geometry +391+261 -composite \
  "$OUT/colors/emerald/tiles/emerald_48.png" -geometry +456+261 -composite \
  "$OUT/colors/emerald/tiles/emerald_49.png" -geometry +521+261 -composite \
  "$OUT/colors/emerald/tiles/emerald_50.png" -geometry +586+261 -composite "$OUT/emerald-reconstructed.png"
mkdir -p "$OUT/colors/lapis_lazuli/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(45,85,155)" -colorize 100 "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_01.png" -geometry +1+1 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_02.png" -geometry +66+1 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_03.png" -geometry +131+1 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_04.png" -geometry +196+1 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_05.png" -geometry +261+1 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_06.png" -geometry +326+1 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_07.png" -geometry +391+1 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_08.png" -geometry +456+1 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_09.png" -geometry +521+1 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_10.png" -geometry +586+1 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_11.png" -geometry +1+66 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_12.png" -geometry +66+66 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_13.png" -geometry +131+66 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_14.png" -geometry +196+66 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_15.png" -geometry +261+66 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_16.png" -geometry +326+66 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_17.png" -geometry +391+66 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_18.png" -geometry +456+66 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_19.png" -geometry +521+66 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_20.png" -geometry +586+66 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_21.png" -geometry +1+131 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_22.png" -geometry +66+131 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_23.png" -geometry +131+131 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_24.png" -geometry +196+131 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_25.png" -geometry +261+131 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_26.png" -geometry +326+131 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_27.png" -geometry +391+131 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_28.png" -geometry +456+131 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_29.png" -geometry +521+131 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_30.png" -geometry +586+131 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_31.png" -geometry +1+196 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_32.png" -geometry +66+196 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_33.png" -geometry +131+196 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_34.png" -geometry +196+196 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_35.png" -geometry +261+196 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_36.png" -geometry +326+196 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_37.png" -geometry +391+196 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_38.png" -geometry +456+196 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_39.png" -geometry +521+196 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_40.png" -geometry +586+196 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_41.png" -geometry +1+261 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_42.png" -geometry +66+261 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_43.png" -geometry +131+261 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_44.png" -geometry +196+261 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_45.png" -geometry +261+261 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_46.png" -geometry +326+261 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_47.png" -geometry +391+261 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_48.png" -geometry +456+261 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_49.png" -geometry +521+261 -composite \
  "$OUT/colors/lapis_lazuli/tiles/lapis_lazuli_50.png" -geometry +586+261 -composite "$OUT/lapis_lazuli-reconstructed.png"
mkdir -p "$OUT/colors/sulfur/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(210,200,60)" -colorize 100 "$OUT/colors/sulfur/tiles/sulfur_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/sulfur/tiles/sulfur_01.png" -geometry +1+1 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_02.png" -geometry +66+1 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_03.png" -geometry +131+1 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_04.png" -geometry +196+1 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_05.png" -geometry +261+1 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_06.png" -geometry +326+1 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_07.png" -geometry +391+1 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_08.png" -geometry +456+1 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_09.png" -geometry +521+1 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_10.png" -geometry +586+1 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_11.png" -geometry +1+66 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_12.png" -geometry +66+66 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_13.png" -geometry +131+66 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_14.png" -geometry +196+66 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_15.png" -geometry +261+66 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_16.png" -geometry +326+66 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_17.png" -geometry +391+66 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_18.png" -geometry +456+66 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_19.png" -geometry +521+66 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_20.png" -geometry +586+66 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_21.png" -geometry +1+131 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_22.png" -geometry +66+131 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_23.png" -geometry +131+131 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_24.png" -geometry +196+131 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_25.png" -geometry +261+131 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_26.png" -geometry +326+131 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_27.png" -geometry +391+131 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_28.png" -geometry +456+131 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_29.png" -geometry +521+131 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_30.png" -geometry +586+131 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_31.png" -geometry +1+196 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_32.png" -geometry +66+196 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_33.png" -geometry +131+196 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_34.png" -geometry +196+196 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_35.png" -geometry +261+196 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_36.png" -geometry +326+196 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_37.png" -geometry +391+196 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_38.png" -geometry +456+196 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_39.png" -geometry +521+196 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_40.png" -geometry +586+196 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_41.png" -geometry +1+261 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_42.png" -geometry +66+261 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_43.png" -geometry +131+261 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_44.png" -geometry +196+261 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_45.png" -geometry +261+261 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_46.png" -geometry +326+261 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_47.png" -geometry +391+261 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_48.png" -geometry +456+261 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_49.png" -geometry +521+261 -composite \
  "$OUT/colors/sulfur/tiles/sulfur_50.png" -geometry +586+261 -composite "$OUT/sulfur-reconstructed.png"
mkdir -p "$OUT/colors/gold/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(200,170,60)" -colorize 100 "$OUT/colors/gold/tiles/gold_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/gold/tiles/gold_01.png" -geometry +1+1 -composite \
  "$OUT/colors/gold/tiles/gold_02.png" -geometry +66+1 -composite \
  "$OUT/colors/gold/tiles/gold_03.png" -geometry +131+1 -composite \
  "$OUT/colors/gold/tiles/gold_04.png" -geometry +196+1 -composite \
  "$OUT/colors/gold/tiles/gold_05.png" -geometry +261+1 -composite \
  "$OUT/colors/gold/tiles/gold_06.png" -geometry +326+1 -composite \
  "$OUT/colors/gold/tiles/gold_07.png" -geometry +391+1 -composite \
  "$OUT/colors/gold/tiles/gold_08.png" -geometry +456+1 -composite \
  "$OUT/colors/gold/tiles/gold_09.png" -geometry +521+1 -composite \
  "$OUT/colors/gold/tiles/gold_10.png" -geometry +586+1 -composite \
  "$OUT/colors/gold/tiles/gold_11.png" -geometry +1+66 -composite \
  "$OUT/colors/gold/tiles/gold_12.png" -geometry +66+66 -composite \
  "$OUT/colors/gold/tiles/gold_13.png" -geometry +131+66 -composite \
  "$OUT/colors/gold/tiles/gold_14.png" -geometry +196+66 -composite \
  "$OUT/colors/gold/tiles/gold_15.png" -geometry +261+66 -composite \
  "$OUT/colors/gold/tiles/gold_16.png" -geometry +326+66 -composite \
  "$OUT/colors/gold/tiles/gold_17.png" -geometry +391+66 -composite \
  "$OUT/colors/gold/tiles/gold_18.png" -geometry +456+66 -composite \
  "$OUT/colors/gold/tiles/gold_19.png" -geometry +521+66 -composite \
  "$OUT/colors/gold/tiles/gold_20.png" -geometry +586+66 -composite \
  "$OUT/colors/gold/tiles/gold_21.png" -geometry +1+131 -composite \
  "$OUT/colors/gold/tiles/gold_22.png" -geometry +66+131 -composite \
  "$OUT/colors/gold/tiles/gold_23.png" -geometry +131+131 -composite \
  "$OUT/colors/gold/tiles/gold_24.png" -geometry +196+131 -composite \
  "$OUT/colors/gold/tiles/gold_25.png" -geometry +261+131 -composite \
  "$OUT/colors/gold/tiles/gold_26.png" -geometry +326+131 -composite \
  "$OUT/colors/gold/tiles/gold_27.png" -geometry +391+131 -composite \
  "$OUT/colors/gold/tiles/gold_28.png" -geometry +456+131 -composite \
  "$OUT/colors/gold/tiles/gold_29.png" -geometry +521+131 -composite \
  "$OUT/colors/gold/tiles/gold_30.png" -geometry +586+131 -composite \
  "$OUT/colors/gold/tiles/gold_31.png" -geometry +1+196 -composite \
  "$OUT/colors/gold/tiles/gold_32.png" -geometry +66+196 -composite \
  "$OUT/colors/gold/tiles/gold_33.png" -geometry +131+196 -composite \
  "$OUT/colors/gold/tiles/gold_34.png" -geometry +196+196 -composite \
  "$OUT/colors/gold/tiles/gold_35.png" -geometry +261+196 -composite \
  "$OUT/colors/gold/tiles/gold_36.png" -geometry +326+196 -composite \
  "$OUT/colors/gold/tiles/gold_37.png" -geometry +391+196 -composite \
  "$OUT/colors/gold/tiles/gold_38.png" -geometry +456+196 -composite \
  "$OUT/colors/gold/tiles/gold_39.png" -geometry +521+196 -composite \
  "$OUT/colors/gold/tiles/gold_40.png" -geometry +586+196 -composite \
  "$OUT/colors/gold/tiles/gold_41.png" -geometry +1+261 -composite \
  "$OUT/colors/gold/tiles/gold_42.png" -geometry +66+261 -composite \
  "$OUT/colors/gold/tiles/gold_43.png" -geometry +131+261 -composite \
  "$OUT/colors/gold/tiles/gold_44.png" -geometry +196+261 -composite \
  "$OUT/colors/gold/tiles/gold_45.png" -geometry +261+261 -composite \
  "$OUT/colors/gold/tiles/gold_46.png" -geometry +326+261 -composite \
  "$OUT/colors/gold/tiles/gold_47.png" -geometry +391+261 -composite \
  "$OUT/colors/gold/tiles/gold_48.png" -geometry +456+261 -composite \
  "$OUT/colors/gold/tiles/gold_49.png" -geometry +521+261 -composite \
  "$OUT/colors/gold/tiles/gold_50.png" -geometry +586+261 -composite "$OUT/gold-reconstructed.png"
mkdir -p "$OUT/colors/silver/tiles"
for i in {01..50}; do
  magick "$OUT/tmp/base_${i}.png" -colorspace gray -fill "rgb(180,185,190)" -colorize 100 "$OUT/colors/silver/tiles/silver_${i}.png"
done
magick -size 651x326 canvas:black \
  "$OUT/colors/silver/tiles/silver_01.png" -geometry +1+1 -composite \
  "$OUT/colors/silver/tiles/silver_02.png" -geometry +66+1 -composite \
  "$OUT/colors/silver/tiles/silver_03.png" -geometry +131+1 -composite \
  "$OUT/colors/silver/tiles/silver_04.png" -geometry +196+1 -composite \
  "$OUT/colors/silver/tiles/silver_05.png" -geometry +261+1 -composite \
  "$OUT/colors/silver/tiles/silver_06.png" -geometry +326+1 -composite \
  "$OUT/colors/silver/tiles/silver_07.png" -geometry +391+1 -composite \
  "$OUT/colors/silver/tiles/silver_08.png" -geometry +456+1 -composite \
  "$OUT/colors/silver/tiles/silver_09.png" -geometry +521+1 -composite \
  "$OUT/colors/silver/tiles/silver_10.png" -geometry +586+1 -composite \
  "$OUT/colors/silver/tiles/silver_11.png" -geometry +1+66 -composite \
  "$OUT/colors/silver/tiles/silver_12.png" -geometry +66+66 -composite \
  "$OUT/colors/silver/tiles/silver_13.png" -geometry +131+66 -composite \
  "$OUT/colors/silver/tiles/silver_14.png" -geometry +196+66 -composite \
  "$OUT/colors/silver/tiles/silver_15.png" -geometry +261+66 -composite \
  "$OUT/colors/silver/tiles/silver_16.png" -geometry +326+66 -composite \
  "$OUT/colors/silver/tiles/silver_17.png" -geometry +391+66 -composite \
  "$OUT/colors/silver/tiles/silver_18.png" -geometry +456+66 -composite \
  "$OUT/colors/silver/tiles/silver_19.png" -geometry +521+66 -composite \
  "$OUT/colors/silver/tiles/silver_20.png" -geometry +586+66 -composite \
  "$OUT/colors/silver/tiles/silver_21.png" -geometry +1+131 -composite \
  "$OUT/colors/silver/tiles/silver_22.png" -geometry +66+131 -composite \
  "$OUT/colors/silver/tiles/silver_23.png" -geometry +131+131 -composite \
  "$OUT/colors/silver/tiles/silver_24.png" -geometry +196+131 -composite \
  "$OUT/colors/silver/tiles/silver_25.png" -geometry +261+131 -composite \
  "$OUT/colors/silver/tiles/silver_26.png" -geometry +326+131 -composite \
  "$OUT/colors/silver/tiles/silver_27.png" -geometry +391+131 -composite \
  "$OUT/colors/silver/tiles/silver_28.png" -geometry +456+131 -composite \
  "$OUT/colors/silver/tiles/silver_29.png" -geometry +521+131 -composite \
  "$OUT/colors/silver/tiles/silver_30.png" -geometry +586+131 -composite \
  "$OUT/colors/silver/tiles/silver_31.png" -geometry +1+196 -composite \
  "$OUT/colors/silver/tiles/silver_32.png" -geometry +66+196 -composite \
  "$OUT/colors/silver/tiles/silver_33.png" -geometry +131+196 -composite \
  "$OUT/colors/silver/tiles/silver_34.png" -geometry +196+196 -composite \
  "$OUT/colors/silver/tiles/silver_35.png" -geometry +261+196 -composite \
  "$OUT/colors/silver/tiles/silver_36.png" -geometry +326+196 -composite \
  "$OUT/colors/silver/tiles/silver_37.png" -geometry +391+196 -composite \
  "$OUT/colors/silver/tiles/silver_38.png" -geometry +456+196 -composite \
  "$OUT/colors/silver/tiles/silver_39.png" -geometry +521+196 -composite \
  "$OUT/colors/silver/tiles/silver_40.png" -geometry +586+196 -composite \
  "$OUT/colors/silver/tiles/silver_41.png" -geometry +1+261 -composite \
  "$OUT/colors/silver/tiles/silver_42.png" -geometry +66+261 -composite \
  "$OUT/colors/silver/tiles/silver_43.png" -geometry +131+261 -composite \
  "$OUT/colors/silver/tiles/silver_44.png" -geometry +196+261 -composite \
  "$OUT/colors/silver/tiles/silver_45.png" -geometry +261+261 -composite \
  "$OUT/colors/silver/tiles/silver_46.png" -geometry +326+261 -composite \
  "$OUT/colors/silver/tiles/silver_47.png" -geometry +391+261 -composite \
  "$OUT/colors/silver/tiles/silver_48.png" -geometry +456+261 -composite \
  "$OUT/colors/silver/tiles/silver_49.png" -geometry +521+261 -composite \
  "$OUT/colors/silver/tiles/silver_50.png" -geometry +586+261 -composite "$OUT/silver-reconstructed.png"
magick -size 2644x1018 canvas:"rgb(245,245,245)" \
  "$OUT/lignite-reconstructed.png" -geometry +20+20 -composite \
  "$OUT/quartz-reconstructed.png" -geometry +671+20 -composite \
  "$OUT/magnetite-reconstructed.png" -geometry +1322+20 -composite \
  "$OUT/hematite-reconstructed.png" -geometry +1973+20 -composite \
  "$OUT/cinnabar-reconstructed.png" -geometry +20+346 -composite \
  "$OUT/olivine-reconstructed.png" -geometry +671+346 -composite \
  "$OUT/malachite-reconstructed.png" -geometry +1322+346 -composite \
  "$OUT/emerald-reconstructed.png" -geometry +1973+346 -composite \
  "$OUT/lapis_lazuli-reconstructed.png" -geometry +20+672 -composite \
  "$OUT/sulfur-reconstructed.png" -geometry +671+672 -composite \
  "$OUT/gold-reconstructed.png" -geometry +1322+672 -composite \
  "$OUT/silver-reconstructed.png" -geometry +1973+672 -composite "$OUT/custom-colors-master-sheet.png"
cat > "$OUT/order.txt" <<'EOF'
lignite: (92, 70, 50)
quartz: (210, 210, 200)
magnetite: (58, 63, 69)
hematite: (110, 35, 30)
cinnabar: (200, 70, 80)
olivine: (120, 150, 60)
malachite: (40, 150, 90)
emerald: (0, 140, 90)
lapis_lazuli: (45, 85, 155)
sulfur: (210, 200, 60)
gold: (200, 170, 60)
silver: (180, 185, 190)
EOF
